### PR TITLE
Vega

### PR DESCRIPTION
**Pull request by VegaRobotics**

### CODE REVIEW

**Comment by VegaRobotics** [comment]
Authorized.

**Comment by rafa-smaciel** [comment]
ok.

**Review by VegaRobotics — COMMENTED** [review]
ok

**Comment by rafa-smaciel** [comment]
Aproved.

**Comment by rafa-smaciel** [comment]
Aproved.

**Comment by rafa-smaciel** [comment]
Aproved.

**Comment by rafa-smaciel** [comment]
Aproved.

**Pull request merged**
